# Generated by Django 5.1.3 on 2024-11-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='orders',
        ),
    ]
